#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Clean damBreakMod
(

    case=damBreakMod

    mkdir back
    mkdir back/constant/
    mkdir back/constant/polyMesh

    cd $case

    mv 0 ../back/
    mv system ../back/

    mv constant/dynamicMeshDict ../back/constant/
    mv constant/g ../back/constant/
    mv constant/transportProperties ../back/constant/
    mv constant/turbulenceProperties ../back/constant/

    mv constant/polyMesh/blockMeshDict ../back/constant/polyMesh/
    cd ..
    rm -rf $case/
    mv back $case
)

# ----------------------------------------------------------------- end-of-file
