#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`


runApplication setFields
#$application 2>&1 | tee "$application.log"
runApplication $application &
#foamMonitor -l postProcessing/residuals/0/residuals.dat
pyFoamPlotWatcher.py log.interFoam

#------------------------------------------------------------------------------
