#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

###########
gnuplot << EOF
set term jpeg 
set out "rghP.jpg"

set title "Static Pressure in (2.186 0.582 108.2)m"
set xlabel "Time (s)"
set ylabel "Pressure (Pa)"
set grid
set datafile separator ","

p "./rghPressure.csv" u 1:2 t 'p' w lines lt 4

EOF
exit
#------------------------------------------------------------------------------
