#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

###########
gnuplot << EOF
set term jpeg 
set out "FlowRate.jpg"

set title "Flow Rate d12.5mm"
set xlabel "Time (s)"
set ylabel "Outlet Flux (kg/s)"
set grid

p "./postProcessing/outletFlux/0/surfaceRegion.dat" u 1:2 t 'Q' w linespoints lt 7


EOF
exit
#------------------------------------------------------------------------------
