sudo: required

language: go

services:
  - docker 

after_success:
  - docker pull mattshax/openfoam-240
  - export here=$(pwd)
  - docker run --name ofd -itv $here:/opt/geawaves:Z mattshax/openfoam-240 bash -c ' cd /opt/geawaves/damBreak && chmod u+w+x Allrun.sh && ./Allrun.sh && exit'
  - ls
