#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

CleanCase () {
  mkdir -p back/constant/polyMesh
  cd ${case=$1}

  for i in 0 system; do
    mv $i ../back/
  done  

  for i in dynamicMeshDict g transportProperties turbulenceProperties; do
    mv constant/$i ../back/constant/
  done

  mv constant/polyMesh/blockMeshDict ../back/constant/polyMesh/

  cd ..

  rm -rf $case/
  mv back $case
}
CleanSnappyCase (){
  mkdir -p back/constant/polyMesh
  mkdir -p back/constant/triSurface
  cd ${case=$1}

  for i in 0 system; do
    mv $i ../back/
  done  

  for i in dynamicMeshDict g transportProperties turbulenceProperties; do
    mv constant/$i ../back/constant/
  done

  mv constant.bM/polyMesh/blockMeshDict ../back/constant/polyMesh/
  mv constant.bM/triSurface/* ../back/constant/triSurface/

  cd ..

  rm -rf $case/
  mv back $case
}
CleanSalomeCase (){
  mkdir -p back/constant/polyMesh/
  cd ${case=$1}
  mv constant/polyMesh/* ../back/constant/polyMesh/
  cleanCase
  mv ../back/constant/polyMesh/ constant/
  cp 0/alpha.water.orig 0/alpha.water
  rm -rf ../back
} 
CleancfMesh () {
  cd ${case=$1}
  cd mesh
  cleanCase
  rm -r constant/polyMesh
  cd ../case
  cleanCase
  cp 0/alpha.water.orig 0/alpha.water
}  
CheckDir () {
  if [ -d "$2" ]; then
    echo "Cleaning case <$2>..."
    $1 $2;
    echo "Case <$2> clean"
  else
    echo "! Directory <$(pwd)/$2> does not exist"
    echo "! Skipping case <$2>"
  fi
}

for f in $@; do
  f=${f%/}
  case $f in
    damBreak           ) CheckDir CleanCase $f ;;
    damBreakFine       ) CheckDir CleanCase $f ;;
    damBreakMod        ) CheckDir CleanCase $f ;;
    damBreakSwiftBlock ) CheckDir CleanCase $f ;;
    damBreakSnappy     ) CheckDir CleanSnappyCase $f;;
	canal3Dcfmesh	   ) CheckDir CleancfMesh $f ;;
	canal3Dsalome	   ) CheckDir CleanSalomeCase $f ;;
    * ) echo "Case <$f> is not supported by this script";;
  esac
done 

# ----------------------------------------------------------------- end-of-file
