#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

###########
gnuplot << EOF
set term jpeg 
set out "FlowRate23.jpg"

set title "Flow Rate d12.5mm"
set xlabel "Time (s)"
set ylabel "Outlet Flux (kg/s·m²)"
set grid

p "./postProcessing/outletFlux/2.3/surfaceRegion.dat" u 1:2 t 'Q/A' w linespoints lt 7


EOF
exit
#------------------------------------------------------------------------------
